### PR TITLE
Change ubuntu version requirements

### PR DESCRIPTION
**Pull request by vfjpl**
https://support.steampowered.com/kb_article.php?ref=1504-QHXN-8366

"
Important:

Currently, Steam for Linux is only supported on the most recent version of Ubuntu LTS with the Unity, Gnome, or KDE desktops.
"

### CODE REVIEW

**Comment by alex19712207** [comment]
does't work on Ubuntu18.04
AMD 2x 2,63 ATLON 5000+ RAM 4 Gb CeForce 7300 CT
[bootstrap_log.txt](https://github.com/ValveSoftware/steam-for-linux/files/2706189/bootstrap_log.txt)

**Comment by EthanWeegee** [comment]
`Latest Ubuntu LTS` would imply that 16.04 will not work, which is false.

**Comment by julienbenjamin** [comment]
@EthanWeegee No, it means that Valve only official support the lastest version of Ubuntu LTS. Period. It is the platform they are targeting when trying to make everything works. It does not mean it will not work on Debian, or even Arch, it is just not meant directly to be, and these are not targeted as the platform they intent to provide assistance for, at the very least not first.

**Comment by EthanWeegee** [comment]
The latest Ubuntu LTS doesn't use Unity anymore, that needs updated.

**Pull request closed without merging**
