### PR TITLE
Give commands according to Ubuntu version

### PR DESCRIPTION
**Pull request by hms5232**
Give corresponding commands according to different versions of users.
16.04 or later: `apt install gdebi-core`
before 16.04: `apt-get install gdebi-core`

### CODE REVIEW

**Comment by davidak** [comment]
`apt-get` still works in later versions, right? don't make it more complicated for users than needed.

**Comment by hms5232** [comment]
Umm...`apt-get` works indeed, but Ubuntu and Debian recommend using `apt` instead of `apt-get`. I thinks `apt` is more friendly than `apt-get`. For beginner, it is even more so. 
[Requirements in README](https://github.com/ValveSoftware/steam-for-linux#hardware-and-software-requirements)  about OS says "**Latest Ubuntu LTS, fully updated**". The latest Ubuntu version is 19.04, and the LTS version is 18.04. Both of them recommend `apt`. Maybe change commend to `apt` and remove `apt-get`?
English is not my native language; please excuse typing errors. Thanks for talking with me :)

**Comment by mohsin-hazen-ai** [comment]
This looks good to me. **apt** is much better than **apt-get**.

**Comment by kolayne** [comment]
IMHO, the text becomes harder to read after this update. I guess, it's enough to replace apt with apt-get in the original readme, to make it work on any Ubuntu version

**Comment by TriMoon** [comment]
> @kolayne 
> IMHO, the text becomes harder to read after this update. I guess, it's enough to replace apt with apt-get in the original readme, to make it work on any Ubuntu version

I think you mean the otherway around: replace `apt-get` with `apt` :wink:

**Comment by kolayne** [comment]
@TriMoon `apt-get` works on both old and new versions of Ubuntu. `apt` only works on 16.04 or later. So, to make the readme correct for any Ubuntu, it must contain instructions with `apt-get`

**Comment by lucifertdark** [comment]
Isn't apt-get officially deprecated in favour of apt from 16.04 onwards?

**Comment by davidak** [comment]
@lucifertdark deprecated don't mean it's already removed.

Ubuntu 14.04 LTS is supported until 2022 so we should use only **apt-get** until then.

That works for users that just copy the command and don't care. Advanced users might use apt instead if they like to.

**Comment by TriMoon** [comment]
@davidak so this PR is the right way to go :wink:

**Comment by hms5232** [comment]
oh, I remember that Ubuntu 14.04 support `apt` command. Just then, I install Ubuntu 14.04.6 on VirtualBox and guess that happened? The `apt` command is **pre-installed** and work!

If apt version is 1.0 or later, you can use `apt` command. [Ref link](https://mvogt.wordpress.com/2014/04/04/apt-1-0/)

**Comment by braiam** [comment]
Note for future readers: apt-get would not go any time soon. When apt was introduced it was meant as a more user friendly option to different tools provided by apt. apt-get is the preferred method for scripting, since its interface is stable. apt commands can change at any moment:

> SCRIPT USAGE AND DIFFERENCES FROM OTHER APT TOOLS
>        The apt(8) commandline is designed as an end-user tool and it may
>        change behavior between versions. While it tries not to break backward
>        compatibility this is not guaranteed either if a change seems
>        beneficial for interactive use.
> 
>        All features of apt(8) are available in dedicated APT tools like apt-
>        get(8) and apt-cache(8) as well.  apt(8) just changes the default
>        value of some options (see apt.conf(5) and specifically the Binary
>        scope). So you should prefer using these commands (potentially with
>        some additional options enabled) in your scripts as they keep backward
>        compatibility as much as possible.
> 

Notably, there's no depreciation of apt-get.

**Comment by TriMoon** [comment]
> @braiam 
> Notably, there's no depreciation of apt-get.

See https://github.com/ValveSoftware/steam-for-linux/pull/6111#issuecomment-576365739 and the next reply :wink:

**Comment by OdinVex** [comment]
I have noticed that some apt-get situations do not work for apt. I can't recall off-hand what situation but I discovered one while trying to install amdgpu-pro drivers a few months back. I had to manually replace apt with apt-get in the installer.

**Pull request closed without merging**
